name: shellcheck
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.19
        with:
          github_token: ${{ secrets.github_token }}
          path: 'commit-msg'
          pattern: '*'
